name: bencode_dart
description: A Dart library for implementing the encoding and decoding of the Bencode format.
version: 1.0.0
# homepage: none
repository : https://github.com/eclipseglory/bencode_dart
issue_tracker : https://github.com/eclipseglory/bencode_dart/issues

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  test: ^1.14.4
