name: b_encode_decode
description: A Dart library for implementing the encoding and decoding of the Bencode format.
version: 1.0.4
repository: https://github.com/moham96/b_encode_decode
issue_tracker: https://github.com/moham96/b_encode_decode/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.24.3
  lints: ^2.0.1
